{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rhtap-nexus-integration") | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- if $secretData }}
  {{- range .Values.appNamespaces.namespace_prefixes }}
    {{- $namespace := . }}
    {{- range tuple "ci" "development" "prod" "stage" }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: nexus-auth
  namespace: {{ $namespace }}-{{ . }}
data:
  .dockerconfigjson: {{ get $secretData ".dockerconfigjson" }}
    {{- end }}
  {{- end }}
{{- end }}
